load("@prelude//platforms:defs.bzl", "constraint_setting", "constraint_value")

constraint_setting(
    name = "os",
)

constraint_value(
    name = "linux",
    constraint_setting = ":os",
)

constraint_value(
    name = "macos",
    constraint_setting = ":os", 
)

constraint_value(
    name = "windows",
    constraint_setting = ":os",
)